[build]
  # Perintah ini sekarang akan menginstal Flutter terlebih dahulu, lalu membangun aplikasi Anda.
  command = "git clone https://github.com/flutter/flutter.git --depth 1 --branch stable && ./flutter/bin/flutter pub get && ./flutter/bin/flutter build web"
  
  # Direktori publikasi tetap sama.
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
