name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.1.4
  provider: ^6.1.2
  http: ^1.2.1
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  shared_preferences: ^2.2.3
  google_nav_bar: ^5.0.6
  weather: ^3.1.1
  google_fonts: ^6.2.1
  fl_chart: ^1.1.1
  intl: ^0.20.2
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
